/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayerGUI.java
 *
 * Created on Apr 2, 2012, 12:14:15 PM
 */

package us.abaddonsoftware.titanplayer;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import us.abaddonsoftware.bll.*;

/**
 *
 * @author abaddon
 */
public class PlayerGUI extends javax.swing.JFrame {
    /** Creates new form PlayerGUI */
    public PlayerGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mp3Chooser = new javax.swing.JFileChooser();
        previousBtn = new javax.swing.JButton();
        playBtn = new javax.swing.JButton();
        stopBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        libraryList = new javax.swing.JList();
        volumeSlider = new javax.swing.JSlider();
        jScrollPane2 = new javax.swing.JScrollPane();
        playlistList = new javax.swing.JList();
        sortByLabel = new javax.swing.JLabel();
        currentPlaylistLabel = new javax.swing.JLabel();
        savePlaylistBtn = new javax.swing.JButton();
        delPlaylistBtn = new javax.swing.JButton();
        playlistComboBox = new javax.swing.JComboBox();
        sortComboBox = new javax.swing.JComboBox();
        loginLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        trackNameLabel = new javax.swing.JLabel();
        artistNameLabel = new javax.swing.JLabel();
        albumNameLabel = new javax.swing.JLabel();
        totalTimeLabel = new javax.swing.JLabel();
        remainingTimeLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AddToLibraryMenuItem = new javax.swing.JMenuItem();
        AddPlaylistMenuItem = new javax.swing.JMenuItem();
        LoginMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        Mp3Chooser.setFileFilter(new us.abaddonsoftware.bll.MediaFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 200));

        previousBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/abaddonsoftware/titanplayer/prev.png"))); // NOI18N

        playBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/abaddonsoftware/titanplayer/playbutton.png"))); // NOI18N

        stopBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/abaddonsoftware/titanplayer/stop.png"))); // NOI18N

        nextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/abaddonsoftware/titanplayer/next.png"))); // NOI18N

        jScrollPane1.setViewportView(libraryList);

        jScrollPane2.setViewportView(playlistList);

        sortByLabel.setText("Sort by: ");

        currentPlaylistLabel.setText("Current Playlist: ");

        savePlaylistBtn.setText("S");
        savePlaylistBtn.setToolTipText("Save Playlist");

        delPlaylistBtn.setText("D");
        delPlaylistBtn.setToolTipText("Delete Playlist");

        playlistComboBox.setEditable(true);

        sortComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Artist", "Track" }));

        loginLabel.setText("User not currently logged in!");

        trackNameLabel.setText("TrackName");
        jPanel1.add(trackNameLabel);

        artistNameLabel.setText("ArtistName");
        jPanel1.add(artistNameLabel);

        albumNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        albumNameLabel.setText("AlbumName");
        jPanel1.add(albumNameLabel);

        totalTimeLabel.setText("TotalTime");
        jPanel1.add(totalTimeLabel);

        remainingTimeLabel.setText("RemainingTime");
        jPanel1.add(remainingTimeLabel);

        jMenu1.setText("File");

        AddToLibraryMenuItem.setText("Add Song To Library");
        AddToLibraryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToLibraryMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(AddToLibraryMenuItem);

        AddPlaylistMenuItem.setText("Add Playlist");
        jMenu1.add(AddPlaylistMenuItem);

        LoginMenuItem.setText("Login to your Account");
        LoginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenLogin(evt);
            }
        });
        jMenu1.add(LoginMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(volumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(sortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sortByLabel)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(previousBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(playBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(stopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(currentPlaylistLabel)
                                    .addGap(2, 2, 2)
                                    .addComponent(playlistComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(savePlaylistBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(delPlaylistBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(previousBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(volumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sortByLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentPlaylistLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playlistComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(savePlaylistBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delPlaylistBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(10, 10, 10)
                .addComponent(loginLabel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenLogin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenLogin
          UserAccountScreen uas = new UserAccountScreen();
          uas.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_OpenLogin

    private void AddToLibraryMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToLibraryMenuItemActionPerformed
         int returnVal = Mp3Chooser.showOpenDialog(this);
         // TODO add your handling code here:
    }//GEN-LAST:event_AddToLibraryMenuItemActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PlayerGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddPlaylistMenuItem;
    private javax.swing.JMenuItem AddToLibraryMenuItem;
    private javax.swing.JMenuItem LoginMenuItem;
    private javax.swing.JFileChooser Mp3Chooser;
    private javax.swing.JLabel albumNameLabel;
    private javax.swing.JLabel artistNameLabel;
    private javax.swing.JLabel currentPlaylistLabel;
    private javax.swing.JButton delPlaylistBtn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList libraryList;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton playBtn;
    private javax.swing.JComboBox playlistComboBox;
    private javax.swing.JList playlistList;
    private javax.swing.JButton previousBtn;
    private javax.swing.JLabel remainingTimeLabel;
    private javax.swing.JButton savePlaylistBtn;
    private javax.swing.JLabel sortByLabel;
    private javax.swing.JComboBox sortComboBox;
    private javax.swing.JButton stopBtn;
    private javax.swing.JLabel totalTimeLabel;
    private javax.swing.JLabel trackNameLabel;
    private javax.swing.JSlider volumeSlider;
    // End of variables declaration//GEN-END:variables
}
